config/routes.rb
Rails.application.routes.draw do

  root 'commits#index'
  get 'commits' => 'commits#index'
  
end

app/models/commit.rb
class Commit < ActiveRecord::Base
  scope :ref, -> (ref) { where("ref like ?", "%#{ref}%")}
  scope :author, -> (author) { where("name =?", author)}
  scope :date, -> (date) { where("DATE(date) =?", Date.parse(date))}
  scope :order_by_name, -> { order(:name) }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/commits_controller.rb
class CommitsController < ApplicationController
  def index 
    @commits = Commit.all
    filtering_params(params).each do |key, value|
      @commits = @commits.public_send(key, value) if value.present?
    end
  end

  private 
    
    # A list of the param names that can be used for filtering the Commit list
    def filtering_params(params)
      params.slice(:ref, :author, :date)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/commits_helper.rb
module CommitsHelper
  def comment_line(line)
    return line unless line =~ /CR\s(|#|number\s)\d{5}/
    link_text = line.match(/CR\s(|#|number\s)\d{5}/).to_s
    url = 'http://localhost/bugs/'
    if link_text.include?('#') 
      url << link_text.split('#').last
    else
      url << link_text.split(' ').last
    end
    
    line.gsub(link_text, link_to(link_text, url)).html_safe
  end

  def commit_class(commit)
    commit.merge.nil? ? 'commit' : 'commit merge-commit'
  end

  def name_list(commits) 
    commits.collect {|c| [c.name, c.name]}.uniq
  end
end

app/views/commits/_commits.html.erb
<% @commits.each do |commit| %>
  <ul class="<%=commit_class(commit) %>">
    <li> commit <%=commit.ref %></li>
    <% unless commit.merge.nil? %>
      <li> Merge: <%=commit.merge %></li>
    <% end %>
    <li> Author: <%=commit.author %></li>
    <li> Date: <%=commit.date %></li>
    <% commit.comments.split('\n').each do |line|  %>
      <li> <%=comment_line(line) %></li>  
    <% end %>
  </ul>
<% end %> 

app/views/commits/index.html.erb
<div class="row">
  <aside class="col-md-3">
    <section class="search">
      <%= form_tag commits_path, :method => 'get', :id => 'commits_search' do %>
        <%= label_tag :ref, 'Commit Ref' %>
        <%= text_field_tag :ref, params[:ref], class: 'form-control' %>

        <%= label_tag :author %>
        <%= select_tag(:author, options_for_select(name_list(Commit.order_by_name), params[:author]), :include_blank => true, class: 'form-control') %>

        <%= label_tag :date %>(YYYY-MM-DD) 
        <%= text_field_tag :date, params[:date], 'data-provide' => 'datepicker', class: 'form-control' %>

        <%= submit_tag "Search", :name => nil, class: "btn btn-primary" %>
      <% end %>
    </section>
  </aside>
  <div class="col-md-9">
    <div id='commits'><%= render 'commits' %></div>   
  </div>
</div>

app/views/commits/index.js.erb
$("#commits").html("<%= escape_javascript(render("commits")) %>");

app/views/commits/new.html.erb
<h1>Commits#new</h1>
<p>Find me in app/views/commits/new.html.erb</p>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    The <a href="#">Git Log Search</a>
    by Jeffrey Tong
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   '#' %></li>
      <li><%= link_to "Contact", '#' %></li>
      <li><a href="#">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Git Web", '#', id: "logo" %>
    <nav>
      <ul class="nav navbar-nav pull-right">
        <li><%= link_to "Home",   '#' %></li>
        <li><%= link_to "Help",   '#' %></li>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GitWeb</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body>
  <%= render 'layouts/header' %>
  <div class="container">
    <%= yield %>
    <%= render 'layouts/footer' %>
  </div>
</body>
</html>